// <auto-generated />
namespace www.waitservices.com.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class start2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(start2));
        
        string IMigrationMetadata.Id
        {
            get { return "201509121534345_start2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
